// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLjLkWmcyxQaXaLaNw3-_LQ6TOdLyXSk',
    appId: '1:407282843400:web:33b4db50746a90330276bd',
    messagingSenderId: '407282843400',
    projectId: 'my-firebase-toturail',
    authDomain: 'my-firebase-toturail.firebaseapp.com',
    storageBucket: 'my-firebase-toturail.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv8Q9af2Gf5JdZ2B1zgevVsYAmiGuWFrQ',
    appId: '1:407282843400:android:91ca3b4e446d4b9c0276bd',
    messagingSenderId: '407282843400',
    projectId: 'my-firebase-toturail',
    storageBucket: 'my-firebase-toturail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLKNXZFcOcm5M9JtLf7xL85jMkNwhNCMo',
    appId: '1:407282843400:ios:195250c462e797fa0276bd',
    messagingSenderId: '407282843400',
    projectId: 'my-firebase-toturail',
    storageBucket: 'my-firebase-toturail.appspot.com',
    iosBundleId: 'com.example.notification',
  );
}
